
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: sicuenoz/backend
        ports:
        - containerPort: 8000
        env:
        - name: FRONT_URL
          value: http://localhost:30500
        - name: DB_USERNAME
          value: admin
        - name: DB_PASSWORD
          value: admin
        - name: DB_NAME
          value: db
        - name: DB_HOST
          value: db
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30800